#!/bin/bash
# testing the else section
testuser=badtest
if grep $testuser /etc/passwd
then
echo The files for user $testuser are:
ls -a /home/$testuser/.b*
else
echo “The user name $testuser does not exist on this system”
fi
$
$ ./test4
The user name badtest does not exist on this system

