#!/bin/bash
# This script displays the date and who's logged on
echo The time and date are:
date
echo “Let's see who's logged into the system:”
who
$
When you run this script, it produces the following output:
$ ./test1
The time and date are:
Mon Feb 21 15:41:13 EST 2011
Let's see who's logged into the system:
Christine tty2 2011-02-21 15:26
Samantha tty3 2011-02-21 15:26
Timothy tty1 2011-02-21 15:26
user tty7 2011-02-19 14:03 (:0)
user pts/0 2011-02-21 15:21 (:0.0)
