#!/bin/bash
# testing variables
days=10
guest=“Katie”
echo “$guest checked in $days days ago”
days=5
guest=“Jessica”
echo “$guest checked in $days days ago”
$
Running the script produces the following output:
$ chmod u+x test3
$ ./test3
Katie checked in 10 days ago
Jessica checked in 5 days ago
